import { GetStaticProps } from "next";
import { promises as fs } from "fs";
import path from "path";
import matter from "gray-matter";
import Link from "next/link";
import { useState } from "react";
import PlaygroundLayout from "@/components/dashboard/PlaygroundLayout";

interface MeditationSample {
  slug: string;
  personaId: string;
  prompt: string;
  content: string;
}

interface PageProps {
  samples: MeditationSample[];
}

export const getStaticProps: GetStaticProps<PageProps> = async () => {
  const meditationsDir = path.join(
    process.cwd(),
    "scripts/simulate-chatgpt-meditations/meditations"
  );
  const files = await fs.readdir(meditationsDir);

  const samples = await Promise.all(
    files.map(async (filename) => {
      const filePath = path.join(meditationsDir, filename);
      const fileContent = await fs.readFile(filePath, "utf8");
      const { data, content } = matter(fileContent);

      return {
        slug: filename.replace(".md", ""),
        personaId: data["persona-id"] || "",
        prompt: data.prompt || "",
        content: content.trim(),
      };
    })
  );

  return {
    props: {
      samples: samples.sort((a, b) => a.personaId.localeCompare(b.personaId)),
    },
  };
};

export default function ChatGPTMeditationSamples({ samples }: PageProps) {
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedPersona, setSelectedPersona] = useState<string | null>(null);

  const personas = Array.from(new Set(samples.map((s) => s.personaId))).sort();

  const filteredSamples = samples.filter((sample) => {
    const matchesSearch =
      searchTerm === "" ||
      sample.personaId.toLowerCase().includes(searchTerm.toLowerCase()) ||
      sample.prompt.toLowerCase().includes(searchTerm.toLowerCase()) ||
      sample.content.toLowerCase().includes(searchTerm.toLowerCase());

    const matchesPersona =
      !selectedPersona || sample.personaId === selectedPersona;

    return matchesSearch && matchesPersona;
  });

  return (
    <PlaygroundLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl mb-4">ChatGPT Meditation Samples</h1>
          <div className="text-muted-foreground space-y-2 mb-6">
            <p>
              A diverse collection of meditation scripts generated by simulating
              ChatGPT interactions. Each script is generated by combining one of
              20 personas (including software developers, teachers, healthcare
              workers, etc.) with realistic prompts.
            </p>
          </div>
        </div>

        <div className="space-y-4">
          <input
            type="text"
            placeholder="Search by persona, prompt, or content..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full px-4 py-2 rounded-md border border-border bg-background"
          />

          <div className="flex flex-wrap gap-2">
            <button
              onClick={() => setSelectedPersona(null)}
              className={`px-3 py-1 rounded-full text-sm ${
                selectedPersona === null
                  ? "bg-primary text-primary-foreground"
                  : "bg-muted text-muted-foreground"
              }`}
            >
              All Personas
            </button>
            {personas.map((persona) => (
              <button
                key={persona}
                onClick={() => setSelectedPersona(persona)}
                className={`px-3 py-1 rounded-full text-sm ${
                  selectedPersona === persona
                    ? "bg-primary text-primary-foreground"
                    : "bg-muted text-muted-foreground"
                }`}
              >
                {persona}
              </button>
            ))}
          </div>
        </div>

        <div className="mt-8 pt-6 border-t border-border">
          {filteredSamples.length === 0 ? (
            <p className="text-muted-foreground">
              No samples match your search criteria.
            </p>
          ) : (
            <div className="divide-y divide-border">
              {filteredSamples.map((sample) => (
                <Link
                  key={sample.slug}
                  href={`/playground/chatgpt-meditation-samples/${sample.slug}`}
                  className="block py-2 hover:bg-muted/50 transition-colors"
                >
                  <div className="flex gap-6">
                    <div className="w-[180px] shrink-0 text-right">
                      <span className="text-xs text-muted-foreground">
                        {sample.slug}
                      </span>
                    </div>
                    <div className="flex justify-between gap-4 min-w-0">
                      <p className="text-sm leading-normal">{sample.prompt}</p>
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          )}
        </div>
      </div>
    </PlaygroundLayout>
  );
}
